

DEFAULT_AGILE_CENTRAL_SERVER = 'rally1.rallydev.com'
DEFAULT_AC_API_KEY   = '_2QFAQA0wQoSKiORUOsVlMjeQfFr1JkawtItGFHtrtx8'
DEFAULT_AC_WORKSPACE = 'Alligators BLD Unigrations'
DEFAULT_AC_PROJECT   = 'Sandbox'

DEFAULT_JENKINS_SERVER = 'int-win7bldmstr:8080'
DEFAULT_JENKINS_CREDENTIALS = '/'