---
JenkinsBuildConnector:

    AgileCentral:
        Server    :  rally1.rallydev.com
        APIKey    :  _2QFAQA0wQoSKiORUOsVlMjeQfFr1JkawtItGFHtrtx8
        Workspace :  Alligators BLD Unigrations
        Lookback  :  0

    Jenkins:
        Protocol  :  http
        Server    :  tiema03-u183073.ca.com
        Port      :  8080
        API_Token :  e008e30c73820b7eeb097ae1f1fa1dd8
        Username  :  jenkins
        Password  :  encoded-T-m-9-u-Z-Q-=-=
        MaxDepth  :  4
        AgileCentral_DefaultBuildProject :  Jenkins

        Jobs:
            - Job: black-swan-2

        Folders:
            - Folder : Parkour
              AgileCentral_Project: Salamandra


        Views:
            - View: dark flock

    Service:
        Preview       : False
        LogLevel      : DEBUG
        MaxBuilds     : 50
        ShowVCSData   : True

...