
---

JenkinsBuildConnector:

    AgileCentral:
        Server    :  rally1.rallydev.com
        APIKey    :  _2QFAQA0wQoSKiORUOsVlMjeQfFr1JkawtItGFHtrtx8
        Workspace :  Alligators BLD Unigrations

    Jenkins:
        Protocol  : http
        Server    : int-win7bldmstr.f4tech.com
        Port      : 8080
        Prefix    :
        Auth      : false
        AgileCentral_DefaultBuildProject: Sandbox

        Jobs:
            - Job : VCSEIF-git-master

            - Job: WICoCo-master build
              AgileCentral_Project: Dynamic

            - Job: jenkins-rally-build-publisher
              AgileCentral_Project: Static

    Service:
        Preview       : True
        LogLevel      : DEBUG
        MaxBuilds     : 50   # current implementation is this is a per job maximum not total builds
        ShowVCSData   : True

...