
---

JenkinsBuildConnector:

    AgileCentral:
        Server    :  rally1.rallydev.com
        APIKey    :  _2QFAQA0wQoSKiORUOsVlMjeQfFr1JkawtItGFHtrtx8
        Workspace :  Alligators BLD Unigrations

    Jenkins:
        Protocol  : http
        Server    : almci.f4tech.com
        Port      : 80
        Prefix    :
        Auth      : false
       #API_Token : 342gaeg3q4ybv8th4obr8g3afe
       # to get an API_Token, in your browser, navigate to http://server:port/user/<username>/configure
        AgileCentral_DefaultBuildProject: Sandbox

        Folders:
            - Folder : ALM
              #AgileCentral_Project: Engineering
              exclude: backward-compatibility,on-demand

            - Folder : ALM Deploy

            - Folder : Pinata

    Service:
        Preview       : True
        LogLevel      : DEBUG
        MaxBuilds     : 50   # current implementation is this is a per job maximum not total builds
        ShowVCSData   : True

...