# intended to be used for a full connector test
---
JenkinsBuildConnector:

    AgileCentral:
        Server    :  rally1.rallydev.com
        APIKey    :  _2QFAQA0wQoSKiORUOsVlMjeQfFr1JkawtItGFHtrtx8
        Workspace :  Alligators BLD Unigrations

    Jenkins:
        Protocol  :  http
        Server    :  tiema03-u183073.ca.com
        Port      :  8080
        API_Token :  e008e30c73820b7eeb097ae1f1fa1dd8
        Username  :  jenkins
        #Password  :  None
        MaxDepth  :  3
        AgileCentral_DefaultBuildProject :  Manual Test 1

        Jobs:
            - Job: wildland butchery
#
#        Views:
#            - View: Shoreline
#              include: ^B*
#              exclude: ^C*
#
#        Folders:
#            - Folder : Zoolander
#              AgileCentral_Project: Sub Project Manual Test 11
#              include: juvenile
#              exclude: hall of mirrors

    Service:
        Preview       : True
        LogLevel      : DEBUG
        MaxBuilds     : 50
        ShowVCSData   : True

...

