
JenkinsBuildConnector:

    AgileCentral:
        Server    : rally1.rallydev.com
        Username  : henry5@hauslancaster.uk
        Password  : 2MuchAngst1415
        #API_Key   : _zzzyyyy234twqwtqwet89y4t38g38y0  # if you enable this, you don't need the Username and Password entries
        Workspace : My Onliest Workspace
 
    Jenkins:
        Protocol : http
        Server   : jenkado.mydomain.com
        Port     : 8080
        Prefix   :
        Username : yourname
        Password : somepassword
        API_Token: 320ca9ae9408d099183aa052ff3199c2
        # to get an API_Token, nav browser to  http://server:port/user/<username>/configure
        MaxDepth  :  5  # specifies how many folder levels will be supported
        AgileCentral_DefaultBuildProject: Your Project 0
        
        Views:
            - View: Project Omega
              include: ^master-*
              exclude: ^feature-*,fumar,launch
              AgileCentral_Project: Your Project 1
 
            - View: Smoke Tests
              include: smoke-test
              exclude: ^feature-*,burnin
              AgileCentral_Project: Your Project 2
 
        Jobs:
            - Job: Wambots-precalcolo
              AgileCentral_Project: Your Project 3
 
            - Job: fustulum-linter-metrics
              AgileCentral_Project: Your Project 4

        Folders:
            - Folder: Abracadabra
              exclude: barymetrics,preprocessing
            - Folder: Der Splodget
 
    Service:
        Preview     : False
        LogLevel    : INFO
        MaxBuilds   : 100
        ShowVCSData : True
