---
JenkinsBuildConnector:

    AgileCentral:
        Server    : rally1.rallydev.com
        Username  : henry5@hauslancaster.uk
        #Password  : 2MuchAngst1415
        #API_Key   : _zzzyyyy234twqwtqwet89y4t38g38y0
        Workspace : My Onliest Workspace

 
    Jenkins:
        Protocol : http
        Server   : jenkado.mydomain.com
        Port     : 8080
        Prefix   :
        Auth     : false
        #User     : 
        #Password : 
        #API_Token: 320ca9ae9408d099183aa052ff3199c2  
        # to get an API_Token, nav browser to  http://server:port/user/<username>/configure
       AgileCentral_DefaultBuildProject: Connector Devving
        
        Views:
            - View: Project Omega
              include: ^master-*
              exclude: ^feature-*,fumar,launch
              AgileCentral_Project: Funicular
 
            - View: Smoke Tests
              include: smoke-test
              exclude: ^feature-*,burnin
              AgileCentral_Project: Brazen Milliwogs
 
        Jobs:
            - Job: Wambots-precalcolo
              AgileCentral_Project: TPFKA Wombats
 
            - Job: fustulum-linter-metrics
              AgileCentral_Project: Analytics World

        Folders:
            - Folder: Abracadabra
              exclude: barymetrics,preprocessing
            - Folder: Der Splodget
 
     Service:
        Preview: False
        LogLevel: INFO
        StrictProject: False
        MaxBuilds: 200

...

