
---
JenkinsBuildConnector:

    AgileCentral:
        Server    :  rally1.rallydev.com
        APIKey    :  _2QFAQA0wQoSKiORUOsVlMjeQfFr1JkawtItGFHtrtx8
        Workspace :  Alligators BLD Unigrations
        Lookback  :  120

    Jenkins:
        Protocol  :  http
        Server    :  localhost
        Port      :  8080
        API_Token :  bogus
        Username  :  bogus
        Password  :  bogus
        AgileCentral_DefaultBuildProject :  Jenkins
        Lookback  :  30000

        Folders:
            - Folder : pencil

            - Folder : sarajevo
              AgileCentral_Project: Manual Test SVN


    Service:
        Preview       : False
        LogLevel      : DEBUG
        MaxBuilds     : 50
        ShowVCSData   : True

...